[package]
name = "rb-sys"
version = "0.3.1"
edition = "2021"
links = "ruby"
readme = "readme.md"
categories = ["ruby", "external-ffi-bindings"]

[features]
default = []
ruby-static = []
link-ruby = []

[dependencies]
libc = "0.2.112"

[lib]
doctest = false

[build-dependencies]
bindgen = { git = "https://github.com/ianks/rust-bindgen", branch = "allowlist-file" }
pkg-config = "0.3.24"
