[package]
name = "rb-sys"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.112"

[build-dependencies]
bindgen = "0.59.2"

[patch.crates-io]
bindgen = { git = "https://github.com/daviddrysdale/rust-bindgen", branch = "allowlist-file" }