[book]
authors = ["Ian Ker-Seymer"]
language = "en"
src = "src"
title = "The Ruby on Rust Book"
description = "A comprehensive guide to building Ruby extensions with Rust using rb-sys"

[output.html]
git-repository-url = "https://github.com/oxidize-rb/rb-sys"
git-repository-icon = "fa-github"
site-url = "https://oxidize-rb.github.io/rb-sys/"
additional-css = ["theme/css/custom.css"]
additional-js = ["theme/js/custom.js"]

[build]
extra-watch-dirs = ["theme"]

[preprocessor.links]

# Copy robots.txt to the output directory
[[output.html.print.html-before-content]]
text = '''
<!-- This is a placeholder to ensure robots.txt is copied -->
'''
