name: Cache Clean

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed

permissions:
  actions: write

jobs:
  clear-cache:
    runs-on: ubuntu-latest
    steps:
      - name: Delete caches
        uses: actions/github-script@v6
        with:
          script: |
            let currentPage = 1

            while (true) {
              const caches = await github.rest.actions.getActionsCacheList({
                owner: context.repo.owner,
                repo: context.repo.repo,
                per_page: 100,
                ref: context.ref,
                page: currentPage,
              })

              for (const cache of caches.data.actions_caches) {
                const deleted = await github.rest.actions.deleteActionsCacheById({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  cache_id: cache.id,
                })

                console.log(`Deleted cache ${cache.id}`)
              }

              if (caches.data.total_count <= currentPage * 100) {
                break
              }

              currentPage++
            }

            console.log("Clear completed")
